name: Auto Update README

# Trigger on pull request opened/updated AND on pushes to main
on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository using GITHUB_TOKEN with write permissions
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'pull_request_target' && github.head_ref || 'main' }}
          fetch-depth: 0
          persist-credentials: true

      # 2. Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the update_readme.py script
      - name: Run update_readme script
        run: |
          python3 update_readme.py

      # 5. Commit and push changes back (to PR branch or main)
      - name: Commit and push changes
        run: |
          # Configure Git user information
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1. Stash working directory changes (including README.md)
          git stash push --include-untracked -m "auto-update-stash"

          # 2. Determine if this run was triggered by a PR or a push to main, then select target branch
          if [ "${{ github.event_name }}" = "pull_request_target" ]; then
            TARGET_BRANCH="${{ github.head_ref }}"
          else
            TARGET_BRANCH="main"
          fi

          # 3. Fetch the remote target branch and force-checkout to that branch
          git fetch origin "$TARGET_BRANCH"
          git checkout -f "$TARGET_BRANCH"

          # 4. Pop the previously stashed changes and apply them to the current branch
          git stash pop || true

          # 5. Add, commit, and push the updated README.md
          git add README.md
          git commit -m "ci: auto-update README section with latest timestamp"
          git push origin "$TARGET_BRANCH" --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}