name: Auto Update README

# Trigger on pull request opened/updated AND on pushes to main
on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # 1. Clone the repository using GITHUB_TOKEN with write permissions
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'pull_request_target' && github.head_ref || 'main' }}
          fetch-depth: 0
          persist-credentials: true

      # 2. Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # # 4. Run the update_readme.py script
      # - name: Run update_readme script
      #   run: |
      #     python3 update_readme.py

      # # 4. Run the REST-based update_readme script
      # - name: Run update_readme_rest script
      #   run: |
      #     python3 update_readme_rest.py \
      #       ${{ github.repository_owner }} \
      #       ${{ github.event.repository.name }}
      
      # 4. Run the GraphQl-based update_readme script
      - name: Run update_readme_graphql script
        run: |
          python3 update_readme_graphql.py \
            ${{ github.repository_owner }} \
            ${{ github.event.repository.name }}

      # 5. Commit and push changes back (to PR branch or main)
      - name: Commit and push changes
        shell: bash
        run: |
          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1. Stash any working-directory changes
          git stash push --include-untracked -m "auto-update-stash" || true

          # 2. Choose target branch
          if [ "${{ github.event_name }}" = "pull_request_target" ]; then
            TARGET_BRANCH="${{ github.head_ref }}"
          else
            TARGET_BRANCH="main"
          fi

          # 3. Fetch & checkout
          git fetch origin "$TARGET_BRANCH"
          git checkout -f "$TARGET_BRANCH"

          # 4. Restore stashed changes
          git stash pop || true

          # 5. Only commit if README.md changed
          if git diff --quiet README.md; then
            echo "No changes in README.md; skipping commit."
          else
            git add README.md
            git commit -m "ci: auto-update README section with latest timestamp"
            git push origin "$TARGET_BRANCH" --no-verify
          fi